###
@port = 8080
@api = http://localhost:{{port}}

### ADMIN
@auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGliZXIiLCJlbWFpbCI6InRpYmVyQGVtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY3NjIyMTQyOCwiZXhwIjoxNjc2NDgwNjI4fQ.PsERr7IznjzgfsTPTIrPiRG77iSXC4IRlx4f7gY2chc
@admin={{api}}/api/admin
@user=tiber

### LOGIN ADMIN
POST {{admin}}/login
Content-Type: application/json

{
  "user": "tiber",
  "password": "tiber"
}

### GET ADMIN WITH TOKEN
GET {{admin}}/login
Authorization: {{auth}}

### CREATE ADMIN
POST {{admin}}/newuser
Authorization: {{auth}}
Content-Type: application/json

{
    "user": "tiber",
    "name": "da8ah",
    "email": "tiber@email.com",
    "mobile": "+593000000001",
    "password": "tiber"
}

### UPDATE ADMIN
PUT {{admin}}/{{user}}
Authorization: {{auth}}
Content-Type: application/json

{
    "user": "tiber",
    "name": "da8ah"    
}



### BOOKS
@books={{admin}}/books

### GET ALL BOOKS
GET {{books}}
Authorization: {{auth}}

### CREATE BOOK
POST {{books}}
Authorization: {{auth}}
Content-Type: application/json

{
  "isbn": "9780141988511",
  "imgRef": "https://azure.blob.png",
  "title": "12 Rules for Life: An Antidote to Chaos",
  "author": "Peterson, Jordan B.",
  "releaseDate": "16/01/2018",
  "grossPricePerUnit": 25,
  "inOffer": true,
  "discountPercentage": 25,
  "hasIva": false,
  "ivaPercentage": 0,
  "createdDate": "10/01/2023", // Careful MongoModel with Date(mm-dd-yyyy)!
  "description": "JBP's BestSeller",
  "stock": 100,
  "visible": true,
  "recommended": true,
  "bestSeller": true,
  "recent": false
}

###
@isbn = 9780141988511

### UPDATE BOOK
PUT {{books}}/{{isbn}}
Authorization: {{auth}}
Content-Type: application/json

{
  "isbn": "9780141988511",
    "imgRef": "https://azure.blob.png",
    "title": "12 Rules for Life: An Antidote to Chaos",
    "author": "Peterson, Jordan B.",
    "releaseDate": "16/01/2018",
    "grossPricePerUnit": 25,
    "inOffer": true,
    "discountPercentage": 25,
    "hasIva": true,
    "ivaPercentage": 12,
    "createdDate": "2023-10-01T05:00:00.000Z", // (mm-dd-yyyy) || yyyy-dd-mmThh:mm:ss.mlsZ
    "description": "THE MULTI-MILLION COPY BESTSELLER",
    "stock": 100,
    "visible": true,
    "recommended": true,
    "bestSeller": true,
    "recent": false
}

### DELETE BOOK
DELETE {{books}}/{{isbn}}
Authorization: {{auth}}



### TRANSACTIONS
@transactions={{admin}}/transactions

### RETRIEVE ALL TRANSACTIONS
GET {{transactions}}
Authorization: {{auth}}