###
@port = 8080
@api = http://localhost:{{port}}

### ADMIN
@auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGliZXIiLCJlbWFpbCI6InRpYmVyQGVtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY3NTI4MDU2NiwiZXhwIjoxNjc1NTM5NzY2fQ.hDVQXztxk06yiA5lnT8dUATO6ixi95mIr6lLlfCDghw
@admin={{api}}/api/admin
@user=tiber

### LOGIN ADMIN
POST {{admin}}/login
Content-Type: application/json

{
  "user": "tiber",
  "password": "tiber"
}

### GET ADMIN WITH TOKEN
GET {{admin}}/{{user}}
Authorization: {{auth}}

### CREATE ADMIN
POST {{admin}}/newuser
Authorization: {{auth}}
Content-Type: application/json

{
    "user": "tiber",
    "name": "da8ah",
    "email": "tiber@email.com",
    "mobile": "+593000000001",
    "password": "tiber"
}



### BOOKS
@books={{admin}}/books

### CREATE BOOK
POST {{books}}
Content-Type: application/json

{
  "isbn": "9780141988511",
  "imgRef": "https://azure.blob.url",
  "title": "12 Rules for Life: An Antidote to Chaos",
  "author": "Peterson, Jordan B.",
  "releaseDate": "16/01/2018",
  "grossPricePerUnit": 25,
  "inOffer": true,
  "discountPercentage": 25,
  "hasIva": false,
  "ivaPercentage": 0,
  "createdDate": "10/01/2023", // Careful MongoModel with Date(mm-dd-yyyy)!
  "description": "JBP's BestSeller",
  "stock": 100,
  "visible": true,
  "recommended": true,
  "bestSeller": true,
  "recent": false
}

###
@isbn = 9780141988511

### UPDATE BOOK
PUT {{books}}/{{isbn}}
Content-Type: application/json

{
  "description": "THE MULTI-MILLION COPY BESTSELLER",
  "hasIva": false
}

### DELETE BOOK
DELETE {{books}}/{{isbn}}



### TRANSACTIONS
@transactions={{admin}}/transactions

### RETRIEVE ALL TRANSACTIONS
GET {{transactions}}
Authorization: {{auth}}