###
@port = 8080
@api = http://localhost:{{port}}

### CREATE CLIENT
POST {{api}}/signup
Content-Type: application/json

{
    "user": "tiber",
    "name": "da8ah",
    "email": "tiber@email.com",
    "mobile": "+593000000001",
    "password": "tiber",
    "billingInfo": {
      "toWhom": "tiber",
      "ci": "1000000001",
      "provincia": "Loja",
      "ciudad": "Loja",
      "numCasa": "000",
      "calles": "Principal y Secundaria"
    }
}

### LOGIN CLIENT
POST {{api}}/signin
Content-Type: application/json

{
  "user": "tiber",
  "password": "tiber"
}

### CREATE ADMIN
@admin=/api/admin

###
POST {{api}}{{admin}}/signup
Content-Type: application/json

{
    "user": "tiber",
    "name": "da8ah",
    "email": "tiber@email.com",
    "mobile": "+593000000001",
    "password": "tiber"
}

### LOGIN ADMIN
POST {{api}}{{admin}}/login
Content-Type: application/json

{
  "user": "tiber",
  "password": "tiber"
}